# Generated by Django 4.1.6 on 2023-02-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPadministracion', '0004_alter_persona_apellido_alter_persona_correo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='apellido',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cedula',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='celular',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='contra',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='user',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
